spring:
  profiles:
    active: @system.env@

server:
  port: 8083
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

index:
  loginUrl: http://localhost:8083/welcomeToCanopus.html
  browserPath: cmd /c start

#  application:
#    name: ts-bi-service
#  banner:
#    location: classpath:banner.txt
#  dubbo:
#    server: true
#    application:
#      name: bi-consumer-service
#      id: ${spring.dubbo.application.name}

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

#配置mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    use-generated-keys: true
    default-executor-type: reuse
    default-statement-timeout: 600
  mapper-locations: classpath:com/canopus/website/dao/*.xml
  #全局的映射，不用在xml文件写实体类的全路径
  type-aliases-package: com.canopus.website.model



