index:
  open: false
debug: false
trace: false

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://149.28.90.50:3306/website?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: vampire
    password: Vampire@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#  dubbo:
#    registry:
#      address: zookeeper://192.168.20.241:2181

logging:
  level:
    org.apache.ibatis: debug
    springframework.web: debug
    org.springboot.sample: debug
