# 项目启动跳转页面开关
index:
  open: false
#查看springboot开启了哪些配置
debug: false
trace: false

spring:
  profiles: local
  datasource:
    #  切换本地库或者远程库
    #    url: jdbc:mysql://149.28.90.50:3306/website?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    #    username: vampire
    #    password: Vampire@123
    url: jdbc:mysql://localhost:3306/website?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#  dubbo:
#    registry:
#      address: zookeeper://192.168.20.241:2181

logging:
  level:
    org.apache.ibatis: debug
    springframework.web: debug
    org.springboot.sample: debug


